### ISSUE TITLE
Display Last Modified at the Bottom of a Page

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/uwex-media-wp-theme#1]
![screen shot 2015-01-13 at 3 11 58 pm](https://cloud.githubusercontent.com/assets/237349/5729243/a38225de-9b36-11e4-89c1-51cf9ada7132.png)

It would be nice to have it noted when a documentation page was last updated. Could we please have this added to the bottom of Pages? (Not necessarily Posts though). And it would be nice if it was subtle, but still very readable. (I used the <small> tag in the example screenshot)

**For Reference:** http://codex.wordpress.org/Function_Reference/the_modified_date

**Comment by Lin87** [comment]
Added to all pages with the exception of posts.
