### ISSUE TITLE
Content / Sidebar Padding

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/uwex-media-wp-theme#2]
The padding is currently very tight between the page content and the sidebar.

![screen shot 2015-01-13 at 3 13 51 pm](https://cloud.githubusercontent.com/assets/237349/5729263/d0ce1214-9b36-11e4-9eef-2fdb084ffa35.png)

**Comment by Lin87** [comment]
Sidebar now has a new look, and added padding to the page content area.
