### ISSUE TITLE
Responsive Items in the Showcase

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/uwex-media-wp-theme#7]
Can Items like Generic Videos and Storybook Presentations be made to work in a responsive way in the showcase? I know this is a difficult topic with iframes and stuff.

But right now it's awkward to use the side on mobile. At the minimum, is there a clever way to make Generic Video Player videos work in a responsive way?

**Comment by Lin87** [comment]
I am actually working on it at the moment.

**Comment by Lin87** [comment]
Done!
![iframe responsiveness](https://user-images.githubusercontent.com/2531526/40082061-79a88c00-5855-11e8-8569-372b7caf01d8.png)

**Comment by Lin87** [comment]
I will assumed this issue is resolved. Reopen if not.
