### ISSUE TITLE
Link to the a Privacy Policy

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/uwex-media-wp-theme#9]
We should have a privacy policy linked on the website. And I Assume we should just link to one for Extension.

I'm not sure who the authority would be on this, but we should ask them.

**Comment by Lin87** [comment]
@patrick-wirth Thought? I can't find one on ce.uwex.edu as well. We're not collecting any user information using cookies other than Google Analytic.

**Comment by patrick-wirth** [comment]
@Lin87 @owlboy Let's use the DS privacy policy to guide our draft.  Once we have something in place, I can run it by the necessary people.  How does that sound?

URL: https://datasciencedegree.wisconsin.edu/privacy-policy/

**Comment by Lin87** [comment]
Sounds good to me. Do you want me to draft it?
